=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/xml/game_grammar.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- game composed by a list of players + current turn + current board -->
<!ELEMENT game (lobby, turn, board)>

    <!-- list of players -->
    <!ELEMENT lobby (player+)>
        <!ATTLIST lobby
                id ID #REQUIRED>
        <!-- player's nickname to be parsed -->
        <!ELEMENT player (nickname, god?)>
            <!ELEMENT nickname (#PCDATA)>
            <!-- avoiding a deck tag introducing gods within player -->
            <!ELEMENT god (#PCDATA)>

    <!-- current turn where tha game has been stopped, containing the current player -->
    <!ELEMENT turn (player,state)>
        <!-- state name which defines the position in the fsm -->
        <!ELEMENT state (#PCDATA)>

    <!-- current board before the stoppage composed by 25 cells -->
    <!ELEMENT board (cell+)>
        <!-- every cell containing coordinates, level and presence of worker -->
        <!ELEMENT cell (x, y, level, worker?)>
            <!ELEMENT x (#PCDATA)>
            <!ELEMENT y (#PCDATA)>
            <!ELEMENT level (#PCDATA)>
            <!ELEMENT worker (player)>
                <!ATTLIST worker
                        gender (male | female) #REQUIRED>

=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/xml/backup_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE game SYSTEM "game_grammar.dtd">
<game>
    <lobby>
        <player>
            <nickname>Riccardo</nickname>
            <god>PERSEPHONE</god>
            <pawns>
                <worker current="true" gender="male">
                    <x>1</x>
                    <y>2</y>
                </worker>
                <worker current="false" gender="female">
                    <x>4</x>
                    <y>1</y>
                </worker>
            </pawns>
        </player>
        <player>
            <nickname>Fabio</nickname>
            <god>ATHENA</god>
            <pawns>
                <worker current="true" gender="male">
                    <x>0</x>
                    <y>2</y>
                </worker>
                <worker current="false" gender="female">
                    <x>4</x>
                    <y>4</y>
                </worker>
            </pawns>
        </player>
        <player state="chooseWorker">
            <nickname>Mirko</nickname>
            <god>ZEUS</god>
            <pawns>
                <worker current="false" gender="male">
                    <x>0</x>
                    <y>0</y>
                </worker>
                <worker current="true" gender="female">
                    <x>0</x>
                    <y>1</y>
                </worker>
            </pawns>
            <malusList>
                <malus permanent="true">
                    <type>MOVE</type>
                    <forbidden>
                        <direction>UP</direction>
                    </forbidden>
                </malus>
                <malus permanent="false">
                    <type>BUILD</type>
                    <numTurn>5</numTurn>
                    <forbidden>
                        <direction>DOWN</direction>
                    </forbidden>
                </malus>
            </malusList>
        </player>
    </lobby>
    <board>
        <cell>
            <x>0</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>1</y>
            <level>BOTTOM</level>
        </cell>
        <cell>
            <x>0</x>
            <y>2</y>
            <level>MIDDLE</level>
        </cell>
        <cell>
            <x>0</x>
            <y>3</y>
            <level>TOP</level>
        </cell>
        <cell>
            <x>0</x>
            <y>4</y>
            <level>DOME</level>
        </cell>
        <cell>
            <x>1</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
    </board>
</game>

=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/xml/backup_lobby.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE game SYSTEM "game_grammar.dtd">
<game>
    <lobby>
        <player state="move">
            <nickname>ejkcjs</nickname>
            <god>ARTEMIS</god>
            <pawns>
                <worker current="false" gender="male">
                    <x>1</x>
                    <y>1</y>
                </worker>
                <worker current="true" gender="female">
                    <x>2</x>
                    <y>1</y>
                </worker>
            </pawns>
        </player>
        <player>
            <nickname>edvcwe</nickname>
            <god>APOLLO</god>
            <pawns>
                <worker current="true" gender="male">
                    <x>2</x>
                    <y>2</y>
                </worker>
                <worker current="false" gender="female">
                    <x>3</x>
                    <y>2</y>
                </worker>
            </pawns>
        </player>
    </lobby>
    <board>
        <cell>
            <x>0</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
    </board>
</game>

=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/xml/conf_sample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE game SYSTEM
        "/Users/mirkousuelli/OneDrive - Politecnico di Milano/GitHub/SW-Engineering-Project/mirko/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/xml/game_grammar.dtd">

<game>

    <lobby id="RFM1">
        <player>
            <nickname>Riccardo</nickname>
            <god>APOLLO</god>
        </player>
        <player>
            <nickname>Fabio</nickname>
            <god>ZEUS</god>
        </player>
        <player>
            <nickname>Mirko</nickname>
            <god>HEPHAESTUS</god>
        </player>
    </lobby>

    <turn>
        <player>
            <nickname>Mirko</nickname>
        </player>
        <state>CHOOSE_WORKER</state>
    </turn>

    <board>
        <cell>
            <x>0</x>
            <y>0</y>
            <level>GROUND</level>
            <worker gender="male">
                <player>
                    <nickname>Mirko</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>1</y>
            <level>GROUND</level>
            <worker gender="female">
                <player>
                    <nickname>Mirko</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>2</y>
            <level>GROUND</level>
            <worker gender="female">
                <player>
                    <nickname>Fabio</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>2</y>
            <level>GROUND</level>
            <worker gender="male">
                <player>
                    <nickname>Riccardo</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>1</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>1</y>
            <level>GROUND</level>
            <worker gender="female">
                <player>
                    <nickname>Riccardo</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>4</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>4</y>
            <level>GROUND</level>
            <worker gender="male">
                <player>
                    <nickname>Fabio</nickname>
                </player>
            </worker>
        </cell>
    </board>

</game>
