=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/game_grammar.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- game composed by a list of players + current turn + current board -->
<!ELEMENT game (players, turn, board)>

    <!-- list of players -->
    <!ELEMENT players (player+)>
        <!-- player's nickname to be parsed -->
        <!ELEMENT player (#PCDATA)>

    <!-- current turn where tha game has been stopped, containing the current player -->
    <!ELEMENT turn (state, player)>
        <!-- state name which defines the position in the fsm -->
        <!ELEMENT state (#PCDATA)>

    <!-- current board before the stoppage composed by 25 cells -->
    <!ELEMENT board (cell+)>
        <!-- every cell containing coordinates, level and presence of worker -->
        <!ELEMENT cell (x, y, level, worker?)>
            <!ELEMENT x (#PCDATA)>
            <!ELEMENT y (#PCDATA)>
            <!ELEMENT level (#PCDATA)>
            <!ELEMENT worker (player)>

=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/conf_sample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE game SYSTEM "game_grammar.dtd">

<game>

    <players>
        <player>
            <nickname>Riccardo</nickname>
            <god>APOLLO</god>
        </player>
        <player>
            <nickname>Fabio</nickname>
            <god>ZEUS</god>
        </player>
        <player>
            <nickname>Mirko</nickname>
            <god>HEPHAESTUS</god>
        </player>
    </players>

    <turn>
        <player>
            <nickname>Mirko</nickname>
        </player>
        <state>CHOOSE_WORKER</state>
    </turn>

    <board>
        <cell>
            <x>0</x>
            <y>0</y>
            <level>GROUND</level>
            <worker>
                <player>
                    <nickname>Mirko</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>1</y>
            <level>GROUND</level>
            <worker>
                <player>
                    <nickname>Mirko</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>2</y>
            <level>GROUND</level>
            <worker>
                <player>
                    <nickname>Fabio</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>2</y>
            <level>GROUND</level>
            <worker>
                <player>
                    <nickname>Riccardo</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>1</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>1</y>
            <level>GROUND</level>
            <worker>
                <player>
                    <nickname>Riccardo</nickname>
                </player>
            </worker>
        </cell>
        <cell>
            <x>4</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>4</y>
            <level>GROUND</level>
            <worker>
                <player>
                    <nickname>Fabio</nickname>
                </player>
            </worker>
        </cell>
    </board>

</game>

=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/src/main/java/it/polimi/ingsw/server/model/storage/game.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE game SYSTEM "game_grammar.dtd">

<game>

    <players>
        <player></player>
        <player></player>
        <player></player>
    </players>

    <turn>
        <state>CHOOSE_WORKER</state>
        <player></player>
    </turn>

    <board>
        <cell>
            <x>0</x>
            <y>0</y>
            <level>GROUND</level>
            <worker>
                <player></player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>1</y>
            <level>GROUND</level>
            <worker>
                <player></player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>2</y>
            <level>GROUND</level>
            <worker>
                <player></player>
            </worker>
        </cell>
        <cell>
            <x>0</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>0</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>1</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>2</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>3</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>0</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>1</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>2</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>3</y>
            <level>GROUND</level>
        </cell>
        <cell>
            <x>4</x>
            <y>4</y>
            <level>GROUND</level>
        </cell>
    </board>

</game>
