=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/master/Santorini/src/main/java/it/polimi/ingsw/model/cards/xml/gods_grammar.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cards (god*)>
    <!ELEMENT god (name, description, power+)>
            <!ATTLIST god
                id ID #REQUIRED
            >
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>

        <!ELEMENT power (worker, workerpos, effect, timing, constraints, (move | build | malus | win))>
            <!ELEMENT worker EMPTY>
                    <!ATTLIST worker 
                        who (default | unmoved) "default">

            <!ELEMENT workerpos EMPTY>
                    <!ATTLIST workerpos 
                        where (default | ground | middle | top) "default">

            <!ELEMENT effect EMPTY>
                    <!ATTLIST effect 
                        what (build | move | win | malus) #REQUIRED>

            <!ELEMENT timing EMPTY>
                    <!ATTLIST timing 
                        when (additional | startturn | endturn | default) "default">

            <!ELEMENT constraints (numadd?)>
                    <!ATTLIST constraints
                        samecell (true | false) "false"
                        notsamecell (true |false) "false"
                        perimcell (true | false) "false"
                        notperimcell (true | false) "false"
                        underitself (true | false) "false"
                    >
                <!ELEMENT numadd (#PCDATA)>

            <!ELEMENT move EMPTY>
                    <!ATTLIST move 
                        type (swap | push | default) "default"
                    >

            <!ELEMENT build EMPTY>
                    <!ATTLIST move 
                        type (dome | notdome | default) "default"
                    >

            <!ELEMENT malus (numturns?, directions)>
                    <!ATTLIST malus
                        type (build | move) #REQUIRED
                        permanent (true | false) "false"
                        personal (true | false) "false"
                    >
                <!ELEMENT numturns (#PCDATA)>
                <!ELEMENT directions 
                    (north?,
                    northeast?,
                    east?,
                    southeast?,
                    south?,
                    southwest?,
                    west?,
                    northwest?,
                    up?,
                    down?)
                >
                    <!ELEMENT north EMPTY>
                    <!ELEMENT northeast EMPTY>
                    <!ELEMENT east EMPTY>
                    <!ELEMENT southeast EMPTY>
                    <!ELEMENT south EMPTY>
                    <!ELEMENT southwest EMPTY>
                    <!ELEMENT west EMPTY>
                    <!ELEMENT northwest EMPTY>
                    <!ELEMENT up EMPTY>
                    <!ELEMENT down EMPTY>

=== Fabio-Tresoldi/ing-sw-2020-secreti-tresoldi-usuelli/master/Santorini/src/main/java/it/polimi/ingsw/model/cards/xml/gods.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cards SYSTEM "gods_grammar.dtd">

<cards>
    <!-- - - - - - - - - - - - - - - - - - - - - - APOLLO - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="APOLLO">
        <name>Apollo</name>
        <description>Your Worker may move into an opponent Worker’s space by forcing their Worker to the space yours just vacated</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="move"/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <move type="swap"/>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - ARTHEMIS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="ARTHEMIS">
        <name>Arthemis</name>
        <description>Your Worker may move one additional time, but not back to its initial space</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="move"/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints notsamecell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <move/>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - ATHENA - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="ATHENA">
        <name>Athena</name>
        <description>If one of your Workers moved up on your last turn, opponent Workers cannot move up this turn</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="malus"/>
            <!-- when -->
            <timing when="endturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <malus type="move">
                <directions>
                    <up/>
                </directions>
                <numturns>1</numturns>
            </malus>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - ATLAS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="ATLAS">
        <name>Atlas</name>
        <description>Your Worker may build a dome at any level</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="build"/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <build type="dome"/>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - CHRONUS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="CHRONUS">
        <name>Chronus</name>
        <description>You also win when there are at least five Complete Towers on the board</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="win"/>
            <!-- when -->
            <timing when="endturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <win type="fivetower"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - DEMETER - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="DEMETER">
        <name>Demeter</name>
        <description>Your Worker may build one additional time, but not on the same space</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="build"/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints notsamecell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <build/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - HEPHAESTUS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="HEPHAESTUS">
        <name>Hephaestus</name>
        <description>Your Worker may build one additional block (not dome) on top of your first block</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="build"/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints samecell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <build type="notdome"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - HESTIA - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="HESTIA">
        <name>Hestia</name>
        <description>Your Worker may build one additional time, but this cannot be on a perimeter space</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="build"/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints notperimcell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <build/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - MINOTAUR - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="MINOTAUR">
        <name>Minotaur</name>
        <description>Your Worker may move into an opponent Worker’s space, if their Worker can be forced one space straight backwards to an unoccupied space at any level</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="move"/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <move type="push"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - PAN - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="PAN">
        <name>Pan</name>
        <description>You also win if your Worker moves down two or more levels</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="win"/>
            <!-- when -->
            <timing when="endturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <win type="downfromtwo"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - PERSEPHONE - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="PERSEPHONE">
        <name>Persephone</name>
        <description>If possible, at least one Worker must move up this turn</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="malus"/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <malus type="move" permanent="true">
                <directions>
                    <up/>
                </directions>
            </malus>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - PROMETHEUS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="PROMETHEUS">
        <name>Prometheus</name>
        <description>If your Worker does not move up, it may build both before and after moving</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="build"/>
            <!-- when -->
            <timing when="startturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <build/>
        </power>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="malus"/>
            <!-- when -->
            <timing when="startturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <malus type="move" personal="true">
                <directions>
                    <up/>
                </directions>
                <numturns>1</numturns>
            </malus>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - TRITON - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="TRITON">
        <name>Triton</name>
        <description>Each time your Worker moves into a perimeter space, it may immediately move again</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
            <effect what="move"/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints perimcell="true"/>
            <!-- how -->
            <move/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - ZEUS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="ZEUS">
        <name>Zeus</name>
        <description>Your Worker may build a block under itself</description>
        <power>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- what -->
